services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    # image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    image: mysql:8.0.36
    container_name: db
    # command: '--default-authentication-plugin=mysql_native_password'
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # volumes:
    #   - db_data:/var/lib/mysql
    # restart: always
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=someflask
      - MYSQL_DATABASE=flask
      - MYSQL_USER=flask
      - MYSQL_PASSWORD=flask
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 3306
      - 33060
    # ports:
    #   - '3306:3306'
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'
    networks:
      - app-network
      # - backend
  flask:
    build: ./backend
    links:
      - db
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MYSQL_ROOT_PASSWORD=someflask
      - MYSQL_DATABASE=flask
      - MYSQL_USER=flask
      - MYSQL_PASSWORD=flask
    networks:
      - app-network
      # - backend
volumes:
  db_data:

networks:
  app-network:
    driver: bridge
    external: true
  
# networks:
#   backend:
#     driver: overlay
#     ipam:
#       config:
#         - subnet: 192.168.18.0/24
#     attachable: true